language: node_js
node_js:
- v8.9.4
after_script:
- scp -r -o StrictHostKeyChecking=no ./controller 139.199.72.81:/root/xuetong/controller
before_install:
- openssl aes-256-cbc -K $encrypted_426dcab70d30_key -iv $encrypted_426dcab70d30_iv
  -in xuetong_rsa.enc -out ~/.ssh/xuetong_rsa -d
- chmod 600 ~/.ssh/xuetong_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/xuetong_rsa
- cp .travis/ssh_config ~/.ssh/config
- chmod 600 ~/.ssh/config
